# Generated by Django 4.1.7 on 2023-07-04 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.FloatField()),
                ('account_number', models.TextField()),
                ('verified', models.BooleanField()),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number_of_shares', models.BigIntegerField()),
                ('fund_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_price_at_purchase', models.FloatField()),
                ('shares_purchased', models.FloatField()),
                ('fund_of_shares', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fund_purchased', to='web.fund')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_of_share', to='web.account')),
            ],
        ),
    ]
