# Generated by Django 4.1.7 on 2023-07-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='fund_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='sold',
            field=models.BooleanField(null=True),
        ),
    ]
