# Generated by Django 4.1.7 on 2023-07-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_fund_fund_id_share_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='outstanding',
            field=models.BooleanField(null=True),
        ),
    ]
