# Generated by Django 4.1.7 on 2023-07-11 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_share_shares_purchased_share_share_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_of_share', to='web.account'),
        ),
    ]
