# Generated by Django 4.1.7 on 2023-07-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_share_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='current_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_price_at_purchase',
            field=models.FloatField(null=True),
        ),
    ]
