# Generated by Django 4.1.3 on 2023-08-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('withdrawal', 'Withdrawal'), ('deposit', 'Deposit')], default='deposit', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='share',
            name='current_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_price_at_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
