# Generated by Django 4.2.3 on 2023-08-16 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0009_transaction_money_reciever_transaction_money_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='SSN',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_access_token',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('Buy', 'buy'), ('Sell', 'sell')], default='Buy', max_length=10)),
                ('processed', models.BooleanField()),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personOrdering', to=settings.AUTH_USER_MODEL)),
                ('shares_of', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sharesOf', to='web.fund')),
            ],
        ),
    ]
